steps:
  - name: node:18-alpine
    args:
      - install
    entrypoint: npm
  - name: node:18-alpine
    args:
      - test
    entrypoint: npm
  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - >-
        echo $_DOCKERHUB_TOKEN | docker login --username $_DOCKERHUB_USERNAME
        --password-stdin
    entrypoint: bash
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - $_DOCKERHUB_USERNAME/product-api:latest
      - '-t'
      - $_DOCKERHUB_USERNAME/product-api:$COMMIT_SHA
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_DOCKERHUB_USERNAME/product-api:latest
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_DOCKERHUB_USERNAME/product-api:$COMMIT_SHA
  - name: gcr.io/cloud-builders/kubectl
    env:
      - CLOUDSDK_COMPUTE_REGION=$_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER
    args:
      - apply
      - '-f'
      - k8s/deployment.yaml
  - name: gcr.io/cloud-builders/kubectl
    env:
      - CLOUDSDK_COMPUTE_REGION=$_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER
    args:
      - apply
      - '-f'
      - k8s/service.yaml
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _DOCKERHUB_USERNAME: ''
  _DOCKERHUB_TOKEN: ''
  _REGION: us-central1
  _CLUSTER: capstone-project
